name: Deploy Node App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Deploy with PM2
        run: |
          if pm2 describe node-app > /dev/null; then
            pm2 restart node-app
          else
            pm2 start index.js --name node-app
          fi
          pm2 save
